# coding:gbk

kv = {
    '/images/css.{1,2}css"rel="styleshee': 'www.uuu83.com',
    '如果浏览器版本过老访问本站可能会较卡': 'www.aoaolu.com',
    '哥哥射提供最新最快的自拍偷拍': 'www.gelushe.com',
    'href="/jss/style.css">': 'www.600qa.com',
    '<SCRIPT src="/js/index.js" type=text/javascript>': 'www.88xoxo.com',
    'src="/js/layout.js"': 'www.11xxqq.com',
    'href="/templets/.{2,20}/s.css">': 'www.501ee.com',
    'document.writeln\(tongji\)': 'www.777rn.com',
    '奇米影视成人社区': '500didi.com',
    'id="css" href="/css/style..css">': 'www.600qa.com',
    '<div class=.center margintop border clear menu': 'www.11hhss.com',
    '/templets/css/styles.css': 'www.15yiren.com',
    '/templets/.{3,20}/css/style.css': 'www.xx94xx.com',
    '/templets/temsys/css.css': '500didi.com',
    '/css/menu.js': 'www.66nene.com',
    '<div style="display:none"><script type="text/javascript" src="/js/count.js"></script></div>': 'www.cao2cao.com',
    'href="/css/acss.css"/>': 'www.laojiu.org',
    '<link href="/css/dy.css"': '',
    'src="/sxgg/tj.js">': 'www.99seqing.com',
    '<link href="/css/..css"': 'www.haosemao1.com',
    '/css/css/style.css': '',
    'rc="imageabc/index.js"': '',
    'name=GENERATOR content="MSHTML 8.00.6001.19258"': 'www.5iwin7.com',
    '/template/.{3,20}/images/index.css': 'www.ij77.com',
    'imageabc/style..css': 'www.ananlu.com',
    'class=wrap><DIV class=gonggao><DIV id=toubiao>': 'www.66bbbbb.com',
    '.headerArea{height:25%;background': 'www.299rr.com',
    '/template/.{3,20}/images/css..css': 'www.3388d.com',
    '<META name=GENERATOR content="MSHTML 8.00.6001.23486">': 'www.yeyelus.com',
    'href="/imageabc/css.css"': 'www.avxxav.com',
    'ref="/css/list.css"typ': 'www.bbb900.com',
    'href="/template/.{3,20}/images/list.css"': 'www.kw16.com',
    'href="/skins/index.css"': 'www.df.com',
    'images/dy.css"rel="sty': 'www.hrsese.com',
    '/template/.{3,20}/images/css.css': '',
    '/images/.{0,5}sex/style.css': 'www.2se2se.com',
    '/template/.{3,20}/images/style.css': 'www.babamao.com',
    'href="/css/new.css"rel': 'www.zheduoyan.com',
    '.headerArea{background': 'www.7766e.com',
    'centerdh margintop border cleardh adspic top': 'www.dd858.com',
    '/skins/.{2,4}/images/index.css': 'www.zhizhishe.com',
    'template/.{3,20}/images/style...css': 'www.21ribi.com',
    'template/.{3,20}/images/style..css': 'www.667hh.com',
    '<META content="MSHTML 6.00.2900.5512" name=GENERATOR>': 'www.678kj.com',
    'bgcolor="#DBF1D4">': 'www.quanminlu.com',
    'href="/css/style.css"rel="styleshe': 'www.luergea.com',
    'href="/static/css/base.css"': 'www.henav.com',
    '/templets/.{3,12}/images/index.css': 'www.4gbbb.com',
    # 此站点和678kj看似一个,其实为完全不同呃两个站点
    '/templets/.{2,12}/images/astyle.css': 'www.678pa.com',
    '/skin/images/style.css': 'www.seee2.com',
    '禁止中国人士请勿进入': 'kk1xx.net',
    '<META name=GENERATOR content="MSHTML 9.00.8112.16447">': '444dada.com',
    '/styles/c..css': 'www.2014rrr.com',
    '<link href="/images/list.css" type=text/css rel=stylesheet>': '',
    '/templets/.{3,12}/images/list.css': 'www.mmseba.com',
    'rel="stylesheet" type="text/css" id="css" href=""': 'www.yeyelus.com',
    'href="/imageabc/.{3,12}css"rel': '',
    '/theme/.{6,12}/css/style.css': 'www.543ev.com',
    '/Tpl/.{3,12}//images/index.css': 'www.lupiaopiao.com',
    # 中祥原始该类下www.68danai.com明显不是同类
    'template/default/template.css': 'dy.kanav001.com',
    '/skins/.{2,6}/images/style.css': '',
    '"激情五月 色播五月 色五月 开心五月 丁香五月 五月婷婷 深爱五月"': 'www.gegeri.com',
    'gemgsx.com/css/index.css"': 'www.678qw.com',
    '/template/.{5,10}/images/layout.css': 'www.wowo22.com',
    '/template/default/images/css/style.css': '',
    '<div class="copyright">为了你的健康未成年人访问请自觉离开': 'www.11lala.com',
    '/templets/files/css.css': 'se.haole018.com',
    '.menu a{ float:left; width:80px; text-align:center; padding:8px 0px 6px 0px; font-size:14px;': 'www.lualu2.com',
    'href="/template/se/images/list.css"': 'www.400se.info',
    '"/template/index.css"': 'www.365mav.com',
    '/template/paody/css/style.css': 'www.avtt3.org',
    '/template/.{5,10}/images/\w{8,}.css': 'www.avavkan.com',
    'href="/template/../images/style.css"rel': 'www.322uu.com',
    '<body bgcolor="#C0C0C0">': 'www.luluduo.com',
    '/templets/[2-9]{3,5}/images/style.css': 'www.977uuu.com',
    '<td height="60" bgcolor="#DDF4CE"><font size="5"><strong>': '',
    'href="/Tpl/.{2,5}/images/list.css"': 'www.sqqq1.com',
    '<LINK id=css rel=stylesheet type=text/css href="/css/style1.css">': 'www.588se.com'
}
